name = "guestbook-worker"
main = "index.js"              
compatibility_date = "2025-04-22"

[[d1_databases]]
binding = "DB"
database_name = "guestbook"
database_id = "82c2d0c7-bc28-402f-aa64-878f30e07e50"
