name = "guestbook-worker"
compatibility_date = "2024-04-01"
migrations_dir = "migrations"

[[d1_databases]]
binding = "DB"  # This is what your Worker script will use
database_name = "guestbook"
database_id = "your-d1-database-id"
